# fly.toml app configuration file generated for wandering-violet-7260 on 2023-11-03T22:14:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wandering-violet-7260"
primary_region = "lhr"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
